%macro rsm_main();
filename in 'C:\export_store\S4_all.stmx';
%rsm_import_store(l3_1003,in);
%if &rsm_rc = -1 %then %do;
	%put export of Store unsuccessful;
 %end;
 %else %do;
 	%put export of Store successful;
 %end;
%mend;
%rsm_main();
